### ISSUE TITLE
ome2singletiff error on windows, histocat conversion errors.

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/imctools#27] opened 2018-08-01 19:31 UTC
Hello. I am working on the IMCpipeline and the imc2tiff conversion successfully completed! 

Now, I am working off the IMCpipeline in particular this section
 if do_histocat:
    if not(os.path.exists(folder_histocat)):
        os.makedirs(folder_histocat)
    ome2micat.omefolder2micatfolder(folder_ome, folder_histocat, dtype='uint16')

I do have the imctools with this script successfully installed. 
python -m imctools.scripts.ome2micat -h
usage: ome2micat [-h] [--mask_folder MASK_FOLDER] [--mask_suffix MASK_SUFFIX]
                 [--imagetype {None,uint16,int16,float}]
                 ome_folder out_folder

Convertes an ome folder (or file) to a micat folder

positional arguments:
  ome_folder            A folder with ome images or a single ome file
  out_folder            Folder to output the micat folders

optional arguments:
  -h, --help            show this help message and exit
  --mask_folder MASK_FOLDER
                        Folder containing the masks, or single mask file.
  --mask_suffix MASK_SUFFIX
                        suffix of the mask tiffs
  --imagetype {None,uint16,int16,float}
                        The output image type

However when I issue the command to convert the ome.tiffs to HistoCAT compatible files, there is an error.

>>> folder_ome
'C:/Users/Mohan/Desktop/testing/OUTPUT\\ometiff'
>>> folder_histocat
'C:/Users/Mohan/Desktop/testing/OUTPUT\\histocat'
>>> ome2micat.omefolder2micatfolder(folder_ome, folder_histocat, dtype='uint16')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Mohan\Anaconda3\lib\site-packages\imctools\scripts\ome2micat.py", line 72, in omefolder2micatfolder
    ome2micatfolder(path_ome, outfolder, path_mask=path_mask, dtype=dtype)
  File "C:\Users\Mohan\Anaconda3\lib\site-packages\imctools\scripts\ome2micat.py", line 39, in ome2micatfolder
    ome2singletiff(path_ome, outfolder,basename='', dtype=dtype)
  File "C:\Users\Mohan\Anaconda3\lib\site-packages\imctools\scripts\ome2micat.py", line 15, in ome2singletiff
    ome = ometiffparser.OmetiffParser(path_ome)
  File "C:\Users\Mohan\Anaconda3\lib\site-packages\imctools\io\ometiffparser.py", line 22, in __init__
    self.read_image(original_file)
  File "C:\Users\Mohan\Anaconda3\lib\site-packages\imctools\io\ometiffparser.py", line 46, in read_image
    self.ome = tif.pages[0].tags['image_description'].value
KeyError: 'image_description'
>>>

####
I have tifffile installed 
tifffile                  0.15.1                   py36_1    conda-forge
>python -V
Python 3.6.4 :: Anaconda, Inc.

I have CellProfiler Desktop app installed version 2.2.0.    
My question is that the error is related to ometiffparser, how can I debug this?  is this related to my tifffile version?  What should be the dtype parameter for a windows OS?  

Thank you very much,

SIncerely,
AC

**Comment by arcolombo** [comment] 2018-08-02 02:11
so I looked into this a bit further on my end.

the main issue was the read_image definition within OmetiffParser class, namely the slot 'image_description' did not exist on these tiff-files that I am looking at.

def read_image(self, filename):
        with tifffile.TiffFile(filename) as tif:
            self.data = tif.asarray()
            self.ome = tif.pages[0].tags['image_description'].value


When I traced the read_image call, I can see the structure of the tiff-file, and observed that there is a slot "ImageDescription", and not "image_description".

 with tifffile.TiffFile(filename) as tif:
...   omy = tif.pages[0].tags
...
>>> omy
{'NewSubfileType': <tifffile.tifffile.TiffTag object at 0x000001FC18D387C8>, 'ImageWidth': <tifffile.tifffile.TiffTag object at 0x000001FC18D38818>, 'ImageLength': <tifffile.tifffile.TiffTag object at 0x000001FC18D38868>, 'BitsPerSample': <tifffile.tifffile.TiffTag object at 0x000001FC18D388B8>, 'Compression': <tifffile.tifffile.TiffTag object at 0x000001FC18D38908>, 'PhotometricInterpretation': <tifffile.tifffile.TiffTag object at 0x000001FC18D38958>, 'ImageDescription': <tifffile.tifffile.TiffTag object at 0x000001FC18D389A8>, 'ImageDescription1': <tifffile.tifffile.TiffTag object at 0x000001FC18D389F8>, 'StripOffsets': <tifffile.tifffile.TiffTag object at 0x000001FC18D38A98>, 'SamplesPerPixel': <tifffile.tifffile.TiffTag object at 0x000001FC18D38AE8>, 'RowsPerStrip': <tifffile.tifffile.TiffTag object at 0x000001FC18D38B38>, 'StripByteCounts': <tifffile.tifffile.TiffTag object at 0x000001FC18D38B88>, 'XResolution': <tifffile.tifffile.TiffTag object at 0x000001FC18D38BD8>, 'YResolution': <tifffile.tifffile.TiffTag object at 0x000001FC18D38C28>, 'ResolutionUnit': <tifffile.tifffile.TiffTag object at 0x000001FC18D38C78>, 'Software': <tifffile.tifffile.TiffTag object at 0x000001FC18D38CC8>, 'DateTime': <tifffile.tifffile.TiffTag object at 0x000001FC18D38D18>, 'SampleFormat': <tifffile.tifffile.TiffTag object at 0x000001FC18D38D68>}

If I change the definition to pick up this difference, the read_image works correctly.

  def read_image(self, filename):
        with tifffile.TiffFile(filename) as tif:
            self.data = tif.asarray()
            self.ome = tif.pages[0].tags['ImageDescription'].value

> with tifffile.TiffFile(filename) as tif:
...   omy=tif.pages[0].tags['ImageDescription'].value
...
>>> omy
'<ome:OME xmlns:ns2="http://www.openmicroscopy.org/Schemas/BinaryFile/2013-06s" xmlns:om="openmicroscopy.org/OriginalMetadata" xmlns:ome="http://www.openmicroscopy.org/Schemas/ome/2013-06s" xmlns:sa="http://www.openmicroscopy.org/Schemas/sa/2013-06s" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2013-06 http://www.openmicroscopy.org/Schemas/OME/2012-03/ome.xsd">\n  <ome:Image ID="Image:0" Name="Case 8_3938_3_a0.ome.tiff">\n    <ome:AcquisitionDate>2018-08-01T10:27:40.576722</ome:AcquisitionDate>\n    <ome:Pixels DimensionOrder="XYCZT" ID="Pixels:0" SizeC="34" SizeT="1" SizeX="1402" SizeY="1401" SizeZ="1" Type="float">\n<ome:Channel Fluor="In115" ID="Channel:0:0" Name="MembraneIn115Di" SamplesPerPixel="1">\n        <ome:LightPath />\n      </ome:Channel>\n      <ns2:BinData BigEndian="false" Length="0" />\n    <ome:Channel Fluor="Nd142" ID="Channel:0:1" Name="CXCR3Nd142Di" SamplesPerPixel="1" /><ome:Channel Fluor="Nd143" ID="Channel:0:2" Name="VimentinNd143Di" SamplesPerPixel="1" /><ome:Channel Fluor="Nd144" ID="Channel:0:3" Name="CD31Nd144Di" SamplesPerPixel="1" /><ome:Channel Fluor="Nd145" ID="Channel:0:4" Name="TbetNd145Di" SamplesPerPixel="1" /><ome:Channel Fluor="Nd146" ID="Channel:0:5" Name="CD16Nd146Di" SamplesPerPixel="1" /><ome:Channel Fluor="Sm147" ID="Channel:0:6" Name="CD20Sm147Di" SamplesPerPixel="1" /><ome:Channel Fluor="Nd148" ID="Channel:0:7" Name="ICOSNd148Di" SamplesPerPixel="1" /><ome:Channel Fluor="Sm149" ID="Channel:0:8" Name="CCR4Sm149Di" SamplesPerPixel="1" /><ome:Channel Fluor="Nd150" ID="Channel:0:9" Name="PDL1Nd150Di" SamplesPerPixel="1" /><ome:Channel Fluor="Sm152" ID="Channel:0:10" Name="CD34Sm152Di" SamplesPerPixel="1" /><ome:Channel Fluor="Eu153" ID="Channel:0:11" Name="Lag3Eu153Di" SamplesPerPixel="1" /><ome:Channel Fluor="Sm154" ID="Channel:0:12" Name="Tim3Sm154Di" SamplesPerPixel="1" /><ome:Channel Fluor="Gd155" ID="Channel:0:13" Name="CD45RAGd155Di" SamplesPerPixel="1" /><ome:Channel Fluor="Gd156" ID="Channel:0:14" Name="CD4Gd156Di" SamplesPerPixel="1" /><ome:Channel Fluor="Gd158" ID="Channel:0:15" Name="p-Stat3Gd158Di" SamplesPerPixel="1" /><ome:Channel Fluor="Tb159" ID="Channel:0:16" Name="CD68Tb159Di" SamplesPerPixel="1" /><ome:Channel Fluor="Gd160" ID="Channel:0:17" Name="Histone3Gd160Di" SamplesPerPixel="1" /><ome:Channel Fluor="Dy162" ID="Channel:0:18" Name="CD8Dy162Di" SamplesPerPixel="1" /><ome:Channel Fluor="Dy163" ID="Channel:0:19" Name="FOXP3Dy163Di" SamplesPerPixel="1" /><ome:Channel Fluor="Dy164" ID="Channel:0:20" Name="CD15Dy164Di" SamplesPerPixel="1" /><ome:Channel Fluor="Ho165" ID="Channel:0:21" Name="CD30Ho165Di" SamplesPerPixel="1" /><ome:Channel Fluor="Er166" ID="Channel:0:22" Name="EphrinB2Er166Di" SamplesPerPixel="1" /><ome:Channel Fluor="Er167" ID="Channel:0:23" Name="Granzym BEr167Di" SamplesPerPixel="1" /><ome:Channel Fluor="Er168" ID="Channel:0:24" Name="Ki67Er168Di" SamplesPerPixel="1" /><ome:Channel Fluor="Tm169" ID="Channel:0:25" Name="CD206Tm169Di" SamplesPerPixel="1" /><ome:Channel Fluor="Er170" ID="Channel:0:26" Name="CD3Er170Di" SamplesPerPixel="1" /><ome:Channel Fluor="Yb171" ID="Channel:0:27" Name="CXCR5Yb171Di" SamplesPerPixel="1" /><ome:Channel Fluor="Yb172" ID="Channel:0:28" Name="PDL2Yb172Di" SamplesPerPixel="1" /><ome:Channel Fluor="Yb173" ID="Channel:0:29" Name="CD45ROYb173Di" SamplesPerPixel="1" /><ome:Channel Fluor="Yb174" ID="Channel:0:30" Name="HLADRYb174Di" SamplesPerPixel="1" /><ome:Channel Fluor="Lu175" ID="Channel:0:31" Name="PD1NAT105Lu175Di" SamplesPerPixel="1" /><ome:Channel Fluor="Ir191" ID="Channel:0:32" Name="DNA2Ir191Di" SamplesPerPixel="1" /><ome:Channel Fluor="Ir193" ID="Channel:0:33" Name="DNAIr193Di" SamplesPerPixel="1" /></ome:Pixels>\n  </ome:Image>\n  <sa:StructuredAnnotations><sa:XMLAnnotation ID="8636c1ad-decd-4ef0-ab1e-ad8b991d3d54"><sa:Value><om:OriginalMetadata><om:Key>MCD-XML</om:Key><om:Value /></om:OriginalMetadata></sa:Value></sa:XMLAnnotation></sa:StructuredAnnotations>\n</ome:OME>'



My question is:
1) do all TiffFiles have the same structure to be detected as 'image_description' ?
2) is this error I had specific to my tiff-files? or my tifffile package version?

THANK YOU VERY MUCH

AC

**Comment by votti** [comment] 2018-08-02 07:01
Hey arcolombo,

Thanks for reporting the issue!
This is a duplicate of issue #22 - it originates from a change in the `tifffile` library.

This is already fixed in the development branch of `imctools`
Could you try to install the development branch:
`pip install git+https://github.com/BodenmillerGroup/imctools.git@development`
and report back if this fixes the issue?

**Comment by arcolombo** [comment] 2018-08-02 16:55
your patch in the read_image worked on my end wonderfully. very clean.

thank you for your elegance dearest sir.

Sincerely,
AC
please close

**Comment by votti** [comment] 2018-08-03 08:41
Thanks for the bug report!

**Closed by votti** 2018-08-03 08:41 UTC
